'\" t
.TH "GCLOUD\-COMPUTE\-NETWORKS\-GET" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-networks-get \- Get Google Compute Engine networks
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute networks get\fR
  [NAME_REGEX \&...]
  [\-\-fields FIELDS [FIELDS \&...]]
  [\-\-format FORMAT; default="yaml"]
  [\-\-limit LIMIT]
  [\-\-raw\-links]
  [\-\-sort\-by SORT_BY]
  [\-h, \-\-help]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute networks get\fR displays all data associated with Google Compute Engine networks in a project\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fI[NAME_REGEX \&...]\fR
.RS 4
Name regular expressions used to filter the resources fetched\&. The regular expressions must conform to the re2 syntax (see
https://code\&.google\&.com/p/re2/wiki/Syntax)\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-fields\fR \fIFIELDS [FIELDS \&...]\fR
.RS 4
Fields to display\&. Possible values are:
.sp
.if n \{\
.RS 4
.\}
.nf
IPv4Range
creationTimestamp
description
gatewayIPv4
id
kind
name
selfLink
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specifies the display format\&. By default, resources are printed in YAML format\&. The "text" and "yaml" formats print data as they are fetched from the server, so these formats feel more responsive\&. The "json" format delays printing until all data is collected into a single list, so it may feel less responsive\&.
.RE
.PP
\fB\-\-limit\fR \fILIMIT\fR
.RS 4
The maximum number of results\&.
.RE
.PP
\fB\-\-raw\-links\fR
.RS 4
If provided, resource references in output from the server will not be condensed for readability\&. For example, when listing operations, if a targetLink is \(lqhttps://www\&.googleapis\&.com/compute/v1/projects/my\-project/zones/us\-central2\-a/instances/my\-instance\(rq, \(lqus\-central2\-a/instances/my\-instance\(rq is shown for brevity\&. This behavior can be turned off using this flag\&.
.RE
.PP
\fB\-\-sort\-by\fR \fISORT_BY\fR
.RS 4
A field to sort by\&. To perform a descending\-order sort, prefix the value of this flag with a tilde (\(lq~\(rq)\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
