'\" t
.TH "GCLOUD\-COMPUTE\-FORWARDING\-RULES" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-forwarding-rules \- Read and manipulate forwarding rules to send traffic to load balancers
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute forwarding\-rules\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBcreate\fR
.RS 4
Create a forwarding rule to direct network traffic to a load balancer\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete forwarding rules\&.
.RE
.PP
\fBget\fR
.RS 4
Display detailed information about forwarding rules\&.
.RE
.PP
\fBlist\fR
.RS 4
List forwarding rules\&.
.RE
.PP
\fBset\-target\fR
.RS 4
Modify a forwarding rule to direct network traffic to a new target\&.
.RE
