'\" t
.TH "GCLOUD\-COMPUTE\-URL\-MAPS" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-url-maps \- List, create, and delete URL maps
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute url\-maps\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBcreate\fR
.RS 4
Create a URL map\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete backend services\&.
.RE
.PP
\fBedit\fR
.RS 4
Modify URL maps\&.
.RE
.PP
\fBget\fR
.RS 4
Get URL maps\&.
.RE
.PP
\fBlist\fR
.RS 4
List URL maps\&.
.RE
