'\" t
.TH "GCLOUD\-COMPONENTS\-RESTORE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-components-restore \- Restore the state of the Cloud SDK as it was before the most recent components update, or removal\&. Can only backtrack one step\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud components restore\fR
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
