'\" t
.TH "GCLOUD\-COMPUTE\-TARGET\-POOLS" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-target-pools \- Read and manipulate Google Compute Engine target poolsto handle network load balancing
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute target\-pools\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBadd\-health\-checks\fR
.RS 4
Add a health check to a target pool\&.
.RE
.PP
\fBadd\-instances\fR
.RS 4
Add instances to a target pool\&.
.RE
.PP
\fBcreate\fR
.RS 4
Create a target pool for network load balancing\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete target pools\&.
.RE
.PP
\fBget\fR
.RS 4
Get target pools\&.
.RE
.PP
\fBget\-health\fR
.RS 4
Get the health of instances in a target pool\&.
.RE
.PP
\fBlist\fR
.RS 4
List target pools\&.
.RE
.PP
\fBremove\-health\-checks\fR
.RS 4
Remove a health check from a target pool\&.
.RE
.PP
\fBremove\-instances\fR
.RS 4
Remove instances from a target pool\&.
.RE
.PP
\fBset\-backup\fR
.RS 4
Set a backup pool for a target pool\&.
.RE
