'\" t
.TH "GCLOUD\-COMPUTE\-TARGET\-INSTANCES" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-target-instances \- Read and manipulate Google Compute Engine virtual target instances
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute target\-instances\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBcreate\fR
.RS 4
Create a target instance for handling traffic from a forwarding rule\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete target instances\&.
.RE
.PP
\fBget\fR
.RS 4
Get target instances\&.
.RE
.PP
\fBlist\fR
.RS 4
List target instances\&.
.RE
