'\" t
.TH "GCLOUD\-COMPUTE\-ZONES" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-zones \- List Google Compute Engine zones
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute zones\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBget\fR
.RS 4
Get Google Compute Engine zones\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine zones\&.
.RE
