'\" t
.TH "GCLOUD\-COMPUTE\-URL\-MAPS\-DELETE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-url-maps-delete \- Delete URL maps
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute url\-maps delete\fR
  NAME [NAME \&...]
  [\-h, \-\-help]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute url\-maps delete\fR deletes one or more URL maps\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME [NAME \&...]\fR
.RS 4
The resources to delete\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
