'\" t
.TH "GCLOUD\-COMPUTE\-SNAPSHOTS\-DELETE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-snapshots-delete \- Delete Google Compute Engine snapshots
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute snapshots delete\fR
  NAME [NAME \&...]
  [\-h, \-\-help]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute snapshots delete\fR deletes one or more Google Compute Engine snapshots\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME [NAME \&...]\fR
.RS 4
The resources to delete\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
