'\" t
.TH "GCLOUD\-CONFIG\-SET" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-config-set \- Set the value for an option, so that Cloud SDK tools can use them as configuration\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud config set\fR
  PROPERTY
  VALUE
  [\-\-global\-only]
  [\-h, \-\-help]
.fi
.SH "POSITIONAL ARGUMENTS"
.PP
\fIPROPERTY\fR
.RS 4
The property to be set\&.
.RE
.PP
\fIVALUE\fR
.RS 4
The value to be set\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-global\-only\fR
.RS 4
Set the option in the global properties file\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
