'\" t
.TH "GCLOUD\-COMPUTE\-OPERATIONS" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-operations \- Read and manipulate Google Compute Engine operations
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute operations\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBget\fR
.RS 4
Get Google Compute Engine operations\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine operations\&.
.RE
