'\" t
.TH "GCLOUD\-COMPUTE\-DISKS" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-disks \- Read and manipulate Google Compute Engine disks
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute disks\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBcreate\fR
.RS 4
Create Google Compute Engine persistent disks\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete Google Compute Engine disks\&.
.RE
.PP
\fBget\fR
.RS 4
Get Google Compute Engine disks\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine persistent disks\&.
.RE
.PP
\fBsnapshot\fR
.RS 4
Snapshot Google Compute Engine disks\&.
.RE
