'\" t
.TH "GCLOUD\-COMPONENTS\-LIST" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-components-list \- List all available components and indicate whether or not they\*(Aqre installed or have updates available\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud components list\fR
  [\-\-show\-versions]
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-show\-versions\fR
.RS 4
Show version information for all components\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
