'\" t
.TH "GCLOUD\-AUTH\-GIT\-HELPER" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-auth-git-helper \- ==SUPPRESS==
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud auth git\-helper\fR
  METHOD
  [\-h, \-\-help]
.fi
.SH "POSITIONAL ARGUMENTS"
.PP
\fIMETHOD\fR
.RS 4
The git credential helper method\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
