'\" t
.TH "GCLOUD\-COMPUTE\-SNAPSHOTS" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-snapshots \- List, get, and delete Google Compute Engine snapshots
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute snapshots\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBdelete\fR
.RS 4
Delete Google Compute Engine snapshots\&.
.RE
.PP
\fBget\fR
.RS 4
Get Google Compute Engine snapshots\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine snapshots\&.
.RE
