'\" t
.TH "GCLOUD\-COMPUTE\-INSTANCES\-DELETE\-ACCESS\-CONFIG" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-instances-delete-access-config \- Delete an access configuration from the network interface of a virtual machine
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute instances delete\-access\-config\fR
  NAME
  [\-\-access\-config\-name ACCESS_CONFIG_NAME; default="external\-nat"]
  [\-\-network\-interface NETWORK_INTERFACE; default="nic0"]
  \-\-zone ZONE
  [\-h, \-\-help]
.fi
.SH "DESCRIPTION"
.sp
\fBgcloud compute instances delete\-access\-config\fR is used to delete access configurations from network interfaces of Google Compute Engine virtual machines\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
The name of the instance from which to delete the access configuration\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-access\-config\-name\fR \fIACCESS_CONFIG_NAME\fR
.RS 4
Specifies the name of the access configuration to delete\&. \(lqexternal\-nat\(rq is used as the default if this flag is not provided\&.
.RE
.PP
\fB\-\-network\-interface\fR \fINETWORK_INTERFACE\fR
.RS 4
Specifies the name of the network interface from which to delete the access configuration\&. If this is not provided, then \(lqnic0\(rq is used as the default\&.
.RE
.PP
\fB\-\-zone\fR \fIZONE\fR
.RS 4
The zone of the instance from which to delete the access configuration\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
