'\" t
.TH "GCLOUD\-COMPUTE\-ADDRESSES" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-compute-addresses \- Read and manipulate Google Compute Engine addresses
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud compute addresses\fR
  COMMAND
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following\&.
.PP
\fBget\fR
.RS 4
Get Google Compute Engine static addresses\&.
.RE
.PP
\fBlist\fR
.RS 4
List Google Compute Engine addresses\&.
.RE
.PP
\fBrelease\fR
.RS 4
Release reserved IP addresses\&.
.RE
.PP
\fBreserve\fR
.RS 4
Reserve IP addresses\&.
.RE
