'\" t
.TH "GCLOUD\-VERSION" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-version \- Print version information for Cloud SDK components\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud version\fR
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
