'\" t
.TH "GCLOUD\-COMPONENTS\-UPDATE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-components-update \- Download and install Cloud SDK components, along with any other components they might depend on\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud components update\fR
  [COMPONENT\-IDS \&...]
  [\-h, \-\-help]
.fi
.SH "POSITIONAL ARGUMENTS"
.PP
\fI[COMPONENT\-IDS \&...]\fR
.RS 4
The component IDs to update or install\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
