'\" t
.TH "GCLOUD\-INTERACTIVE" "1"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
gcloud-interactive \- Run a Python shell where the gcloud CLI is represented by a collection of callable Python objects\&. For instance, to run the command "gcloud auth login", call the function "gcloud\&.auth\&.login()"\&.
.SH "SYNOPSIS"
.sp
.nf
\fBgcloud interactive\fR
  [\-h, \-\-help]
.fi
.SH "FLAGS"
.PP
\fB\-\-help\fR
.RS 4
Print a summary help and exit\&.
.RE
